# Generated by Django 4.2.1 on 2023-05-06 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_id_2',
        ),
        migrations.AddField(
            model_name='existingstudent',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
        migrations.AddField(
            model_name='existingstudent',
            name='full_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
