# Generated by Django 4.2.1 on 2023-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_course_id_2_existingstudent_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingstudent',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
