# Generated by Django 4.2.1 on 2023-05-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_existingstudent_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existingstudent',
            name='full_name',
        ),
        migrations.AddField(
            model_name='existingstudent',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='existingstudent',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
