# Generated by Django 4.2.1 on 2023-06-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_existingstudent_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills', models.CharField(blank=True, max_length=50, null=True)),
                ('plastic', models.CharField(blank=True, max_length=50, null=True)),
                ('avans', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
